### ISSUE TITLE
CORS headers should not be required

### ISSUE THREAD

**Issue by Ekleog** [johannesjo/super-productivity-android#16] opened 2022-02-10 22:24 UTC
Hello!

First, great thanks for Super Productivity, I discovered it yesterday and it feels like an awesome discovery! Sorry for not filling in the whole template, I just feel like it's not really relevant for this “issue”

As per eg. https://github.com/johannesjo/super-productivity/issues/668 , the WebAppPassword app is currently required in order to do WebDAV from the android application. To the best of my understanding, this is due to CORS: Nextcloud explicitly disallows requests from other websites, and so this is security working as designed. WebAppPassword basically weakens this security in order to make Super Productivity work anyway.

However, this does not have to be the case: as there is an actual android app, it should not actually verify CORS headers.

My understanding is that the issue stems from the fact that the WebView is configured to run the webapp from the website directly (thus requiring internet): https://github.com/johannesjo/super-productivity-android/blob/master/app/src/main/java/com/superproductivity/superproductivity/App.java#L43

I think the issue could be solved by bundling the webapp code into the application itself, as this way the URL would be given as `file://` rather than `https://`, and thus be exempt from CORS.

In addition, I'm not sure how exactly the thing works but maybe it would also allow (for free) the app to work without an internet connection, which can always be useful. (Also, this way people could upgrade their app independently from app.superproductivity.com, which is always a nice thing: as I'm personally maybe too much security-conscious I don't feel right allowing superproductivity.com access to all the information in my todo-list, as it contains sensitive information and the website being hacked could lead to this information being exfiltrated)

Would such a change make sense to you?

Anyway, thank you very much from Super Productivity, I've been using it for just a day and I already love it!
Best,
  Léo

**Comment by johannesjo** [comment] 2022-02-11 15:59
Hey @Ekleog ! Thank you very much for opening this up! This is basically a duplicate of #4 

Makes a lot of sense to change this. I wasn't aware that changing to the file protocol disables the cors checks within android (because it doesn't for the browser as far as I know). 

Bundling the app is definitely something I'd like to see as well, but I'd really could use some help,e especially with the android part. There are also two other things to consider: data would need to be migrated from the IndexedDB for app.super-productviity.com to the IndexedDB of file://index.html, which might not be trivial. The other thing is deployment. Deploying to so many platforms is a bit of a hustle. So for this to happen we should also automate as much of the process as possible (via github actions).

**Comment by Ekleog** [comment] 2022-02-12 14:17
Oh I had looked at the issues looking for CORS and missed #4. Sorry about that! Do you want to keep this open to track the fact that the solution to #4 should also solve the WebAppPassword issue (so long as it's configured with [setAllowUniversalAccessFromFileUrls](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/cors-and-webview-api.md#setallowuniversalaccessfromfileurls) or similar)? (I'd lean towards just closing this, but not sure whether the metadata “this should solve the CORS issue” is useful to keep as a github issue to you)

**Comment by johannesjo** [comment] 2022-02-13 18:48
If you're alright with it, I would close this issue :) Thank you!

**Closed as completed by johannesjo** 2022-02-13 18:48 UTC

**Comment by jiongxuan** [comment] 2024-09-04 01:09
My requirements are a bit different, as I primarily need to support self-hosted services and address WebDAV CORS issues during synchronization. As I mentioned earlier, the current approach requires familiarity with Kotlin syntax and involves multiple code changes, which complicates the process.

I plan to write some code soon to ensure quick modifications for self-hosted access. This will allow us to switch to a self-hosted domain and resolve the issue efficiently. Later, I’ll look into how we can handle URL changes and data migration at runtime, but this will require more time to design.

Regarding a fully offline solution, I agree that the changes would be significant, and it’s something that needs careful consideration. We’ll need to take a closer look at how best to approach it.

**Comment by jiongxuan** [comment] 2024-10-09 03:21
@johannesjo @Ekleog @zoli I’ve resolved the issue. Please refer to this PR for details: 

- https://github.com/johannesjo/super-productivity-android/pull/57
- https://github.com/johannesjo/super-productivity/issues/3527

Considering that many are interested, here’s a brief overview of the changes:

I have taken steps to address the longstanding issues related to offline support and CORS in the Android application. These updates are designed to enhance the user experience by enabling offline functionality, resolving security-related CORS issues, and ensuring a smooth transition for existing users. I welcome any questions or feedback from the community to help refine and improve the solution further.
